name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name of the person to greet'
        required: true
        type: string
      greeting:
        description: 'Type of greeting'
        required: true
        type: string
        default: 'Hello'
      data:
        description: 'Base64 encoded content of a file'
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Decode file Content        
        run: |
          echo "${{ github.event.inputs.data }}" | base64 --decode > ./decoded_file.txt
      - name: Display greeting
        run: |
          echo "${{ github.event.inputs.greeting }}, ${{ github.event.inputs.name }}!"
      - name: Display file content
        run: |
           echo "${{ inputs.greeting }}", ${{ inputs.name }}!
      - name: Show decoded file content
        run: |
          if [ -s ./decoded_file.txt ]; then
            echo "Decoded file content:"
            cat ./decoded_file.txt
          else
            echo "No file content provided."
          fi
