name: "Webhook Event"

on: 
    repository_dispatch: 
      types:
        - Webhook
        
jobs:
  respond-to-dispach:     
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Event of type:"  $GITHUB_EVENT_NAME