name: Wrkflow-Commands

on:
  push: 
    branches: 
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Group logging
        run: |
          echo "::group:: Group Message"
          echo "Message 1"
          echo "Message 2"
          echo "::endgroup"

